version: "3.8"

services:
  django_app:
    build:
      context: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 toju_food.wsgi:application
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
