# Generated by Django 5.1.2 on 2024-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
    ]
